"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowRight, ArrowUpRight, CalendarDays, Check, ConciergeBell, MapPin, Minus, Plus, Sparkles, Star, Users } from "lucide-react";
import type { CatalogItem } from "@/db/schema";
import { ItemCard } from "@/components/item-card";
import { tr, useSite } from "@/components/site-shell";

export function HomeClient({ items }: { items: CatalogItem[] }) {
  const { locale, settings } = useSite();
  const router = useRouter();
  const [checkIn, setCheckIn] = useState("");
  const [checkOut, setCheckOut] = useState("");
  const [guests, setGuests] = useState(2);
  const rooms = items.filter((item) => item.category === "accommodation").slice(0, 3);
  const events = [items.find((i) => i.category === "conference_room"), items.find((i) => i.category === "event_hall"), items.find((i) => i.category === "service")].filter(Boolean) as CatalogItem[];
  function search(e: FormEvent) { e.preventDefault(); router.push(`/reservation?${new URLSearchParams({ ...(checkIn ? { checkIn } : {}), ...(checkOut ? { checkOut } : {}), guests: String(guests) })}`); }
  const today = new Date().toISOString().slice(0, 10);
  return <main className="home-page"><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(12,31,27,.76) 0%, rgba(15,36,30,.55) 39%, rgba(13,32,28,.08) 77%),linear-gradient(0deg,rgba(7,29,25,.38),transparent 30%),url('${settings.heroImage}')` }}><div className="container hero-inner"><div className="hero-content"><div className="eyebrow eyebrow-light"><span className="eyebrow-line"/>{tr(locale, "BIENVENUE AU PALACIO HOTEL", "WELCOME TO PALACIO HOTEL")}</div><h1>{locale === "en" ? settings.heroTitleEn : settings.heroTitleFr}</h1><p>{locale === "en" ? settings.heroSubtitleEn : settings.heroSubtitleFr}</p><div className="hero-buttons"><Link href="/reservation" className="btn btn-gold">{tr(locale, "Réserver mon séjour", "Book my stay")} <ArrowUpRight size={17}/></Link><Link href="/hebergements" className="hero-text-link">{tr(locale, "Explorer l’hôtel", "Explore the hotel")} <ArrowRight size={17}/></Link></div></div><div className="hero-side-label"><span>{tr(locale, "DOUALA • CAMEROUN", "DOUALA • CAMEROON")}</span><span className="hero-side-rule"/><span>04°03′ N &nbsp; 09°46′ E</span></div><a href="#decouvrir" className="hero-scroll"><span>{tr(locale, "DÉCOUVRIR", "DISCOVER")}</span><ArrowDown size={16}/></a></div></section>
    <div className="container search-overlap"><form className="search-panel" onSubmit={search}><div className="search-heading"><span className="search-heading-icon"><CalendarDays size={21}/></span><div><span className="search-heading-small">{tr(locale, "ORGANISEZ VOTRE ESCAPADE", "PLAN YOUR GETAWAY")}</span><strong>{tr(locale, "Votre séjour commence ici", "Your stay starts here")}</strong></div></div><label className="search-field"><span>{tr(locale, "ARRIVÉE", "CHECK IN")}</span><input type="date" min={today} value={checkIn} onChange={(e) => { setCheckIn(e.target.value); if (checkOut && checkOut <= e.target.value) setCheckOut(""); }}/></label><label className="search-field"><span>{tr(locale, "DÉPART", "CHECK OUT")}</span><input type="date" min={checkIn || today} value={checkOut} onChange={(e) => setCheckOut(e.target.value)}/></label><div className="search-guests"><span>{tr(locale, "VOYAGEURS", "GUESTS")}</span><div><button type="button" onClick={() => setGuests(Math.max(1, guests - 1))} aria-label="Moins"><Minus size={13}/></button><strong>{guests} {tr(locale, "pers.", "guests")}</strong><button type="button" onClick={() => setGuests(Math.min(20, guests + 1))} aria-label="Plus"><Plus size={13}/></button></div></div><button className="btn btn-primary search-submit" type="submit">{tr(locale, "Voir les disponibilités", "Check availability")}<ArrowRight size={17}/></button></form></div>
    <section className="intro-section section-pad" id="decouvrir"><div className="container intro-grid"><div className="intro-side"><span className="section-number">01 / 04</span><span className="vertical-line"/><span className="vertical-text">{tr(locale, "UNE ADRESSE À PART", "A PLACE APART")}</span></div><div className="intro-main"><div className="eyebrow"><span className="eyebrow-line"/>{tr(locale, "L’ESPRIT PALACIO", "THE PALACIO SPIRIT")}</div><h2 className="section-title">{tr(locale, "L’art de recevoir, la liberté de ", "The art of hospitality, the freedom to ")}<em>{tr(locale, "se sentir chez soi.", "feel at home.")}</em></h2><p>{locale === "en" ? settings.aboutEn : settings.aboutFr}</p><Link href="/pages/notre-histoire" className="text-link">{tr(locale, "Découvrir notre histoire", "Discover our story")}<ArrowUpRight size={17}/></Link></div><div className="intro-stamp"><span>✦</span><strong>PALACIO</strong><small>{tr(locale, "HOSPITALITÉ D’EXCEPTION", "EXCEPTIONAL HOSPITALITY")}</small></div></div></section>
    <section className="rooms-section section-pad"><div className="container"><div className="section-header"><div><div className="eyebrow"><span className="eyebrow-line"/>{tr(locale, "NOS HÉBERGEMENTS", "OUR ACCOMMODATION")}</div><h2 className="section-title">{tr(locale, "Des espaces pensés pour ", "Spaces made for ")}<em>{tr(locale, "vous.", "you.")}</em></h2><p>{tr(locale, "Des chambres et suites où chaque détail raconte une certaine idée du bonheur.", "Rooms and suites where every detail tells a story of effortless comfort.")}</p></div><Link href="/hebergements?categorie=accommodation" className="outline-link">{tr(locale, "Voir tous les hébergements", "View all rooms")}<ArrowUpRight size={17}/></Link></div><div className="cards-grid">{rooms.map((item, index) => <ItemCard key={item.id} item={item} index={index}/>)}</div></div></section>
    <section className="experience-feature"><div className="experience-image"><img src={settings.aboutImage} alt="Palacio Hotel" loading="lazy"/><div className="experience-image-tag"><Star size={14} fill="currentColor"/> {tr(locale, "DES INSTANTS QUI COMPTENT", "MOMENTS THAT MATTER")}</div></div><div className="experience-copy"><span className="section-number light-number">02 / 04</span><div className="eyebrow eyebrow-light"><span className="eyebrow-line"/>{tr(locale, "L’EXPÉRIENCE PALACIO", "THE PALACIO EXPERIENCE")}</div><h2>{tr(locale, "Bien plus qu’un ", "More than a ")}<em>{tr(locale, "séjour.", "stay.")}</em></h2><p>{tr(locale, "Un dîner à savourer sans regarder l’heure. Un moment de calme retrouvé. Une attention qui change tout. Chez nous, les plus beaux souvenirs se vivent dans les détails.", "A dinner to savour without watching the clock. A moment of calm. A thoughtful touch that changes everything. Here, the best memories live in the details.")}</p><div className="experience-highlights"><span><Check size={15}/>{tr(locale, "Hospitalité personnalisée", "Personalized hospitality")}</span><span><Check size={15}/>{tr(locale, "Expériences sur mesure", "Tailored experiences")}</span></div><Link href="/hebergements?categorie=service" className="btn btn-gold">{tr(locale, "Explorer nos expériences", "Explore experiences")}<ArrowUpRight size={17}/></Link></div></section>
    <section className="events-section section-pad"><div className="container"><div className="section-header"><div><div className="eyebrow"><span className="eyebrow-line"/>{tr(locale, "À CHAQUE OCCASION", "FOR EVERY OCCASION")}</div><h2 className="section-title">{tr(locale, "Chaque moment mérite ", "Every moment deserves ")}<em>{tr(locale, "un lieu unique.", "a special place.")}</em></h2><p>{tr(locale, "Réunions inspirantes, célébrations inoubliables et parenthèses bien-être.", "Inspiring meetings, unforgettable celebrations and moments of wellness.")}</p></div></div><div className="events-grid">{events.map((item, i) => <Link href={`/hebergements/${item.slug}`} className="event-tile" key={item.id}><img src={item.image} alt={locale === "en" ? item.nameEn : item.nameFr} loading="lazy"/><div className="event-overlay"><span>0{i+1} / 03</span><h3>{locale === "en" ? item.nameEn : item.nameFr}</h3><div><span>{tr(locale, "Découvrir", "Discover")}</span><ArrowUpRight size={18}/></div></div></Link>)}</div></div></section>
    <section className="quote-banner"><div className="container quote-banner-inner"><div className="quote-banner-content"><div className="eyebrow eyebrow-light"><span className="eyebrow-line"/>{tr(locale, "UN PROJET EN TÊTE ?", "HAVE SOMETHING IN MIND?")}</div><h2>{tr(locale, "Laissez-nous imaginer ", "Let us create ")}<em>{tr(locale, "l’inoubliable.", "the unforgettable.")}</em></h2><p>{tr(locale, "Un événement, un séjour en famille ou une expérience singulière ? Racontez-nous votre projet et recevez une proposition rien qu’à vous.", "An event, a family stay or a unique experience? Tell us your plans and receive a proposal made just for you.")}</p><Link href="/devis" className="btn btn-gold">{tr(locale, "Demander un devis personnalisé", "Request a tailored quote")}<ArrowUpRight size={17}/></Link></div><div className="quote-banner-art"><span className="quote-art-circle">✦</span><span className="quote-art-word">Palacio</span><span className="quote-art-caption">{tr(locale, "VOTRE HISTOIRE COMMENCE ICI", "YOUR STORY STARTS HERE")}</span></div></div></section>
    <section className="closing-section section-pad"><div className="container closing-grid"><div className="closing-photo"><img src="/images/palacio-hero.jpg" alt="Palacio Hotel Douala" loading="lazy"/><div className="closing-photo-badge"><ConciergeBell size={20}/><span>{tr(locale, "Toujours à vos côtés", "Always by your side")}</span></div></div><div className="closing-copy"><div className="eyebrow"><span className="eyebrow-line"/>{tr(locale, "AU CŒUR DE DOUALA", "IN THE HEART OF DOUALA")}</div><h2 className="section-title">{tr(locale, "Un monde à découvrir. ", "A world to discover. ")}<em>{tr(locale, "Le vôtre à retrouver.", "Yours to return to.")}</em></h2><p>{tr(locale, "Idéalement situé à Douala, le Palacio vous ouvre les portes de la ville tout en vous offrant un refuge paisible pour chaque instant de votre séjour.", "Perfectly located in Douala, Palacio opens the city to you while offering a peaceful haven for every moment of your stay.")}</p><div className="closing-address"><MapPin size={18}/><span>{locale === "en" ? settings.addressEn : settings.addressFr}</span></div><Link href="/contact" className="text-link">{tr(locale, "Nous trouver et nous contacter", "Find and contact us")}<ArrowUpRight size={17}/></Link></div></div></section></main>;
}
